### ISSUE TITLE
VLS Crashing constantly

### ISSUE THREAD

**Issue by HarryET** [vlang/vls#113]
# Issue
VLS Crashes when you try and type import with intellisense or open a file with `im` in it

# Editor Info
![image](https://user-images.githubusercontent.com/29015545/115717051-b9df8e80-a371-11eb-8f92-945619683806.png)

# Code
```v
module main
im // Problem line

pub struct Config {
pub mut:
	token string
}

pub struct Client {
	
}

pub fn new(config Config)? &Client {
	// TODO Start the libary
	println(config.token)
}
```

# Error
```
[Info  - 13:45:48] VLS Version: 0.0.1, OS: windows 64
[Info  - 13:45:48] Client / Editor: Visual Studio Code - Insiders 1.56.0-insider
V panic: string.eq(): nil string
v hash: 59e23db
20: v__checker__Checker_fn_call  ?? : address = 0x18244fab68
19: v__checker__Checker_expr   ?? : address = 0x18244fab68
18: v__checker__Checker_fn_call  ?? : address = 0x18244fab68
17: v__checker__Checker_call_expr  ?? : address = 0x18244fab68
16: v__checker__Checker_expr   ?? : address = 0x18244fab68
15: v__checker__Checker_selector_expr  ?? : address = 0x18244fab68
14: v__checker__Checker_selector_expr  ?? : address = 0x18244fab68
13: v__checker__Checker_fn_call  ?? : address = 0x18244fab68
12: v__checker__Checker_selector_expr  ?? : address = 0x18244fab68
11: v__checker__Checker_check  ?? : address = 0x18244fab68
10: v__checker__Checker_check_files  ?? : address = 0x18244fab68
9 : vls__Vls_dispatch          ?? : address = 0x18244fab68
8 : vls__Vls_dispatch          ?? : address = 0x18244fab68
7 : vls__Vls_start_loop        ?? : address = 0x18244fab68
6 : main__Stdio_receive        ?? : address = 0x18244fab68
5 : cli__Command_parse         ?? : address = 0x18244fab68
4 : main__Stdio_receive        ?? : address = 0x18244fab68
3 : wmain                      ?? : address = 0x18244fab68
2 : __scrt_common_main_seh     d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
1 : BaseThreadInitThunk        ?? : address = 0x18244fab68
0 : RtlUserThreadStart         ?? : address = 0x18244fab68
[Info  - 13:45:49] Connection to server got closed. Server will restart.
[Error - 13:45:49] Request textDocument/foldingRange failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\HarryET\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:39411)
	at Object.dispose (c:\Users\HarryET\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119583)
	at w.handleConnectionClosed (c:\Users\HarryET\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119796)
	at w.handleConnectionClosed (c:\Users\HarryET\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:180184)
	at t (c:\Users\HarryET\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:117885)
	at r.invoke (c:\Users\HarryET\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\HarryET\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at Y (c:\Users\HarryET\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:28669)
	at r.invoke (c:\Users\HarryET\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\HarryET\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at fireClose (c:\Users\HarryET\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:53238)
	at Socket.<anonymous> (c:\Users\HarryET\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:54023)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)
[Info  - 13:45:49] VLS Version: 0.0.1, OS: windows 64
[Info  - 13:45:49] Client / Editor: Visual Studio Code - Insiders 1.56.0-insider
V panic: string.eq(): nil string
v hash: 59e23db
20: v__checker__Checker_fn_call  ?? : address = 0xf37696afe8
19: v__checker__Checker_expr   ?? : address = 0xf37696afe8
18: v__checker__Checker_fn_call  ?? : address = 0xf37696afe8
17: v__checker__Checker_call_expr  ?? : address = 0xf37696afe8
16: v__checker__Checker_expr   ?? : address = 0xf37696afe8
15: v__checker__Checker_selector_expr  ?? : address = 0xf37696afe8
14: v__checker__Checker_selector_expr  ?? : address = 0xf37696afe8
13: v__checker__Checker_fn_call  ?? : address = 0xf37696afe8
12: v__checker__Checker_selector_expr  ?? : address = 0xf37696afe8
11: v__checker__Checker_check  ?? : address = 0xf37696afe8
10: v__checker__Checker_check_files  ?? : address = 0xf37696afe8
9 : vls__Vls_dispatch          ?? : address = 0xf37696afe8
8 : vls__Vls_dispatch          ?? : address = 0xf37696afe8
7 : vls__Vls_start_loop        ?? : address = 0xf37696afe8
6 : main__Stdio_receive        ?? : address = 0xf37696afe8
5 : cli__Command_parse         ?? : address = 0xf37696afe8
4 : main__Stdio_receive        ?? : address = 0xf37696afe8
3 : wmain                      ?? : address = 0xf37696afe8
2 : __scrt_common_main_seh     d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
1 : BaseThreadInitThunk        ?? : address = 0xf37696afe8
0 : RtlUserThreadStart         ?? : address = 0xf37696afe8
[Info  - 13:45:49] Connection to server got closed. Server will restart.
[Info  - 13:45:49] VLS Version: 0.0.1, OS: windows 64
[Info  - 13:45:49] Client / Editor: Visual Studio Code - Insiders 1.56.0-insider
V panic: string.eq(): nil string
v hash: 59e23db
20: v__checker__Checker_fn_call  ?? : address = 0x61930faa78
19: v__checker__Checker_expr   ?? : address = 0x61930faa78
18: v__checker__Checker_fn_call  ?? : address = 0x61930faa78
17: v__checker__Checker_call_expr  ?? : address = 0x61930faa78
16: v__checker__Checker_expr   ?? : address = 0x61930faa78
15: v__checker__Checker_selector_expr  ?? : address = 0x61930faa78
14: v__checker__Checker_selector_expr  ?? : address = 0x61930faa78
13: v__checker__Checker_fn_call  ?? : address = 0x61930faa78
12: v__checker__Checker_selector_expr  ?? : address = 0x61930faa78
11: v__checker__Checker_check  ?? : address = 0x61930faa78
10: v__checker__Checker_check_files  ?? : address = 0x61930faa78
9 : vls__Vls_dispatch          ?? : address = 0x61930faa78
8 : vls__Vls_dispatch          ?? : address = 0x61930faa78
7 : vls__Vls_start_loop        ?? : address = 0x61930faa78
6 : main__Stdio_receive        ?? : address = 0x61930faa78
5 : cli__Command_parse         ?? : address = 0x61930faa78
4 : main__Stdio_receive        ?? : address = 0x61930faa78
3 : wmain                      ?? : address = 0x61930faa78
2 : __scrt_common_main_seh     d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
1 : BaseThreadInitThunk        ?? : address = 0x61930faa78
0 : RtlUserThreadStart         ?? : address = 0x61930faa78
[Info  - 13:45:49] Connection to server got closed. Server will restart.
[Info  - 13:45:49] VLS Version: 0.0.1, OS: windows 64
[Info  - 13:45:49] Client / Editor: Visual Studio Code - Insiders 1.56.0-insider
V panic: string.eq(): nil string
v hash: 59e23db
20: v__checker__Checker_fn_call  ?? : address = 0xb5268fb0b8
19: v__checker__Checker_expr   ?? : address = 0xb5268fb0b8
18: v__checker__Checker_fn_call  ?? : address = 0xb5268fb0b8
17: v__checker__Checker_call_expr  ?? : address = 0xb5268fb0b8
16: v__checker__Checker_expr   ?? : address = 0xb5268fb0b8
15: v__checker__Checker_selector_expr  ?? : address = 0xb5268fb0b8
14: v__checker__Checker_selector_expr  ?? : address = 0xb5268fb0b8
13: v__checker__Checker_fn_call  ?? : address = 0xb5268fb0b8
12: v__checker__Checker_selector_expr  ?? : address = 0xb5268fb0b8
11: v__checker__Checker_check  ?? : address = 0xb5268fb0b8
10: v__checker__Checker_check_files  ?? : address = 0xb5268fb0b8
9 : vls__Vls_dispatch          ?? : address = 0xb5268fb0b8
8 : vls__Vls_dispatch          ?? : address = 0xb5268fb0b8
7 : vls__Vls_start_loop        ?? : address = 0xb5268fb0b8
6 : main__Stdio_receive        ?? : address = 0xb5268fb0b8
5 : cli__Command_parse         ?? : address = 0xb5268fb0b8
4 : main__Stdio_receive        ?? : address = 0xb5268fb0b8
3 : wmain                      ?? : address = 0xb5268fb0b8
2 : __scrt_common_main_seh     d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
1 : BaseThreadInitThunk        ?? : address = 0xb5268fb0b8
0 : RtlUserThreadStart         ?? : address = 0xb5268fb0b8
[Info  - 13:45:49] Connection to server got closed. Server will restart.
[Info  - 13:45:49] VLS Version: 0.0.1, OS: windows 64
[Info  - 13:45:49] Client / Editor: Visual Studio Code - Insiders 1.56.0-insider
V panic: string.eq(): nil string
v hash: 59e23db
20: v__checker__Checker_fn_call  ?? : address = 0xafc3afa958
19: v__checker__Checker_expr   ?? : address = 0xafc3afa958
18: v__checker__Checker_fn_call  ?? : address = 0xafc3afa958
17: v__checker__Checker_call_expr  ?? : address = 0xafc3afa958
16: v__checker__Checker_expr   ?? : address = 0xafc3afa958
15: v__checker__Checker_selector_expr  ?? : address = 0xafc3afa958
14: v__checker__Checker_selector_expr  ?? : address = 0xafc3afa958
13: v__checker__Checker_fn_call  ?? : address = 0xafc3afa958
12: v__checker__Checker_selector_expr  ?? : address = 0xafc3afa958
11: v__checker__Checker_check  ?? : address = 0xafc3afa958
10: v__checker__Checker_check_files  ?? : address = 0xafc3afa958
9 : vls__Vls_dispatch          ?? : address = 0xafc3afa958
8 : vls__Vls_dispatch          ?? : address = 0xafc3afa958
7 : vls__Vls_start_loop        ?? : address = 0xafc3afa958
6 : main__Stdio_receive        ?? : address = 0xafc3afa958
5 : cli__Command_parse         ?? : address = 0xafc3afa958
4 : main__Stdio_receive        ?? : address = 0xafc3afa958
3 : wmain                      ?? : address = 0xafc3afa958
2 : __scrt_common_main_seh     d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
1 : BaseThreadInitThunk        ?? : address = 0xafc3afa958
0 : RtlUserThreadStart         ?? : address = 0xafc3afa958
[Error - 13:45:49] Connection to server got closed. Server will not be restarted.
```

**Comment by manen** [comment]
Seems to be the same I observed in #111
