### ISSUE TITLE
unable to use VLS, crashes immediately upon trying to use.

### ISSUE THREAD

**Issue by Th3OneAndOnly** [vlang/vls#162]
I have a log from the output panel:
```

[Info  - 2:54:39 PM] VLS Version: 0.0.1, OS: windows 64
[Info  - 2:54:39 PM] Client / Editor: Visual Studio Code 1.59.0
V panic: array.get: index out of range (i == 100, a.len == 94)
v hash: 6736817
13: array_delete_many          ?? : address = 0x40bdec9b80
12: v__ast__Table_get_type_symbol  ?? : address = 0x40bdec9b70
11: v__ast__Expr_str           ?? : address = 0x40bdec9cc0
10: vinit_string_literals      ?? : address = 0x40bdec9aa0
9 : vls__Vls_dispatch          ?? : address = 0x40bdec9c60
8 : vls__Vls_dispatch          ?? : address = 0x40bdec9a60
7 : vls__Vls_start_loop        ?? : address = 0x40bdec9cb0
6 : main__Stdio_receive        ?? : address = 0x40bdec9be0
5 : cli__Command_parse         ?? : address = 0x40bdec9c40
4 : main__Stdio_receive        ?? : address = 0x40bdec9a10
3 : wmain                      ?? : address = 0x40bdec9ae0
2 : __scrt_common_main_seh     d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
1 : BaseThreadInitThunk        ?? : address = 0x40bdec9c70
0 : RtlUserThreadStart         ?? : address = 0x40bdec9af0
[Info  - 2:54:43 PM] Connection to server got closed. Server will restart.
[Error - 2:54:43 PM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:39411)
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119583)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119796)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:180184)
	at t (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:117885)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at Y (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:28669)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at m.fireClose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:49666)
	at Socket.<anonymous> (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:51251)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 2:54:43 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:39411)
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119583)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119796)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:180184)
	at t (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:117885)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at Y (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:28669)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at m.fireClose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:49666)
	at Socket.<anonymous> (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:51251)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Info  - 2:54:43 PM] VLS Version: 0.0.1, OS: windows 64
[Info  - 2:54:43 PM] Client / Editor: Visual Studio Code 1.59.0
V panic: array.get: index out of range (i == 100, a.len == 94)
v hash: 6736817
13: array_delete_many          ?? : address = 0x2a1accff60
12: v__ast__Table_get_type_symbol  ?? : address = 0x2a1accfee0
11: v__ast__Expr_str           ?? : address = 0x2a1accff20
10: vinit_string_literals      ?? : address = 0x2a1accfe60
9 : vls__Vls_dispatch          ?? : address = 0x2a1acd0070
8 : vls__Vls_dispatch          ?? : address = 0x2a1accfeb0
7 : vls__Vls_start_loop        ?? : address = 0x2a1acd0080
6 : main__Stdio_receive        ?? : address = 0x2a1accfef0
5 : cli__Command_parse         ?? : address = 0x2a1accff90
4 : main__Stdio_receive        ?? : address = 0x2a1accfe50
3 : wmain                      ?? : address = 0x2a1accff00
2 : __scrt_common_main_seh     d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
1 : BaseThreadInitThunk        ?? : address = 0x2a1acd00a0
0 : RtlUserThreadStart         ?? : address = 0x2a1accffd0
[Info  - 2:54:49 PM] Connection to server got closed. Server will restart.
[Error - 2:54:49 PM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:39411)
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119583)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119796)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:180184)
	at t (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:117885)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at Y (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:28669)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at m.fireClose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:49666)
	at Socket.<anonymous> (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:51251)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 2:54:49 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:39411)
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119583)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119796)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:180184)
	at t (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:117885)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at Y (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:28669)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at m.fireClose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:49666)
	at Socket.<anonymous> (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:51251)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Info  - 2:54:49 PM] VLS Version: 0.0.1, OS: windows 64
[Info  - 2:54:49 PM] Client / Editor: Visual Studio Code 1.59.0
V panic: array.get: index out of range (i == 100, a.len == 94)
v hash: 6736817
13: array_delete_many          ?? : address = 0xe9c8138c50
12: v__ast__Table_get_type_symbol  ?? : address = 0xe9c8138c70
11: v__ast__Expr_str           ?? : address = 0xe9c8138d00
10: vinit_string_literals      ?? : address = 0xe9c8138cb0
9 : vls__Vls_dispatch          ?? : address = 0xe9c8138b20
8 : vls__Vls_dispatch          ?? : address = 0xe9c8138b70
7 : vls__Vls_start_loop        ?? : address = 0xe9c8138b90
6 : main__Stdio_receive        ?? : address = 0xe9c8138a60
5 : cli__Command_parse         ?? : address = 0xe9c8138b60
4 : main__Stdio_receive        ?? : address = 0xe9c8138a00
3 : wmain                      ?? : address = 0xe9c8138cc0
2 : __scrt_common_main_seh     d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
1 : BaseThreadInitThunk        ?? : address = 0xe9c8138d60
0 : RtlUserThreadStart         ?? : address = 0xe9c8138b30
[Info  - 2:54:49 PM] Connection to server got closed. Server will restart.
[Error - 2:54:49 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:39411)
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119583)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119796)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:180184)
	at t (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:117885)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at Y (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:28669)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at m.fireClose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:49666)
	at Socket.<anonymous> (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:51251)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 2:54:49 PM] Request textDocument/foldingRange failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:39411)
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119583)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119796)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:180184)
	at t (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:117885)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at Y (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:28669)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at m.fireClose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:49666)
	at Socket.<anonymous> (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:51251)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Info  - 2:54:49 PM] VLS Version: 0.0.1, OS: windows 64
[Info  - 2:54:49 PM] Client / Editor: Visual Studio Code 1.59.0
V panic: array.get: index out of range (i == 100, a.len == 94)
v hash: 6736817
13: array_delete_many          ?? : address = 0x349bbc9650
12: v__ast__Table_get_type_symbol  ?? : address = 0x349bbc96a0
11: v__ast__Expr_str           ?? : address = 0x349bbc95f0
10: vinit_string_literals      ?? : address = 0x349bbc9810
9 : vls__Vls_dispatch          ?? : address = 0x349bbc9890
8 : vls__Vls_dispatch          ?? : address = 0x349bbc9840
7 : vls__Vls_start_loop        ?? : address = 0x349bbc9770
6 : main__Stdio_receive        ?? : address = 0x349bbc95e0
5 : cli__Command_parse         ?? : address = 0x349bbc9920
4 : main__Stdio_receive        ?? : address = 0x349bbc9760
3 : wmain                      ?? : address = 0x349bbc98a0
2 : __scrt_common_main_seh     d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
1 : BaseThreadInitThunk        ?? : address = 0x349bbc96c0
0 : RtlUserThreadStart         ?? : address = 0x349bbc9940
[Info  - 2:54:51 PM] Connection to server got closed. Server will restart.
[Error - 2:54:51 PM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:39411)
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119583)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119796)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:180184)
	at t (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:117885)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at Y (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:28669)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at m.fireClose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:49666)
	at Socket.<anonymous> (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:51251)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 2:54:51 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:39411)
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119583)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119796)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:180184)
	at t (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:117885)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at Y (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:28669)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at m.fireClose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:49666)
	at Socket.<anonymous> (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:51251)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Info  - 2:54:51 PM] VLS Version: 0.0.1, OS: windows 64
[Info  - 2:54:51 PM] Client / Editor: Visual Studio Code 1.59.0
V panic: array.get: index out of range (i == 100, a.len == 94)
v hash: 6736817
13: array_delete_many          ?? : address = 0x4e8a3903f0
12: v__ast__Table_get_type_symbol  ?? : address = 0x4e8a390500
11: v__ast__Expr_str           ?? : address = 0x4e8a390540
10: vinit_string_literals      ?? : address = 0x4e8a390560
9 : vls__Vls_dispatch          ?? : address = 0x4e8a390280
8 : vls__Vls_dispatch          ?? : address = 0x4e8a390410
7 : vls__Vls_start_loop        ?? : address = 0x4e8a3901d0
6 : main__Stdio_receive        ?? : address = 0x4e8a3902f0
5 : cli__Command_parse         ?? : address = 0x4e8a3902d0
4 : main__Stdio_receive        ?? : address = 0x4e8a390400
3 : wmain                      ?? : address = 0x4e8a3903a0
2 : __scrt_common_main_seh     d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
1 : BaseThreadInitThunk        ?? : address = 0x4e8a390210
0 : RtlUserThreadStart         ?? : address = 0x4e8a390300
[Error - 2:54:53 PM] Connection to server got closed. Server will not be restarted.
[Error - 2:54:53 PM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:39411)
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119583)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119796)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:180184)
	at t (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:117885)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at Y (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:28669)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at m.fireClose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:49666)
	at Socket.<anonymous> (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:51251)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 2:54:53 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:39411)
	at Object.dispose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119583)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119796)
	at w.handleConnectionClosed (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:180184)
	at t (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:117885)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at Y (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:28669)
	at r.invoke (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at m.fireClose (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:49666)
	at Socket.<anonymous> (c:\Users\User\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:51251)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)

```
if you need other information, please tell me. Thank you!

**Comment by nedpals** [comment]
@Th3OneAndOnly you are using an old version of VLS which is not actively maintained anymore and now only receives minor patches. Since you are using a 64-bit version of Windows, I encourage you to download and try our new version [here](https://github.com/vlang/vls/releases) :smile:

**Comment by nedpals** [comment]
Ah, my apologies. It got fixed in https://github.com/vlang/vls/commit/5a1413b88f0769980812201f693212877d32c8d1 .
