### ISSUE TITLE
Crash on V code base

### ISSUE THREAD

**Issue by jxxp9** [vlang/vls#231]
From VSCode, installed latest V extension
I have vls.exe in C:\ (dowloaded from Github releases as of https://github.com/vlang/vls/commit/56b3f9299a1f74b68cce60c2bd7af19b1476a22c)

It gives this error on keystroke on V source code:

`[Info  - 00:07:25] VLS Version: 0.0.1-56b3f92, OS: windows 64
[Info  - 00:07:25] Client / Editor: Visual Studio Code 1.60.2
[Info  - 00:07:25] Using V path (VROOT): C:\Users\marco\Documents\v
print_backtrace_skipping_top_frames_mingw is not implemented
[Info  - 00:07:31] Connection to server got closed. Server will restart.
[Error - 00:07:31] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:29:4057)
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:34:9518)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:9073)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:39:12267)
	at n (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:8755)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at rt (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:3:10845)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at Oo.fireClose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:12622)
	at Socket.<anonymous> (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:14174)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 00:07:31] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:29:4057)
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:34:9518)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:9073)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:39:12267)
	at n (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:8755)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at rt (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:3:10845)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at Oo.fireClose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:12622)
	at Socket.<anonymous> (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:14174)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Info  - 00:07:31] VLS Version: 0.0.1-56b3f92, OS: windows 64
[Info  - 00:07:31] Client / Editor: Visual Studio Code 1.60.2
[Info  - 00:07:31] Using V path (VROOT): C:\Users\marco\Documents\v
print_backtrace_skipping_top_frames_mingw is not implemented
[Info  - 00:07:31] Connection to server got closed. Server will restart.
[Error - 00:07:31] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:29:4057)
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:34:9518)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:9073)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:39:12267)
	at n (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:8755)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at rt (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:3:10845)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at Oo.fireClose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:12622)
	at Socket.<anonymous> (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:14174)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 00:07:31] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:29:4057)
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:34:9518)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:9073)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:39:12267)
	at n (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:8755)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at rt (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:3:10845)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at Oo.fireClose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:12622)
	at Socket.<anonymous> (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:14174)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Info  - 00:07:32] VLS Version: 0.0.1-56b3f92, OS: windows 64
[Info  - 00:07:32] Client / Editor: Visual Studio Code 1.60.2
[Info  - 00:07:32] Using V path (VROOT): C:\Users\marco\Documents\v
print_backtrace_skipping_top_frames_mingw is not implemented
[Info  - 00:07:32] Connection to server got closed. Server will restart.
[Error - 00:07:32] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:29:4057)
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:34:9518)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:9073)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:39:12267)
	at n (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:8755)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at rt (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:3:10845)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at Oo.fireClose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:12622)
	at Socket.<anonymous> (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:14174)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 00:07:32] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:29:4057)
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:34:9518)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:9073)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:39:12267)
	at n (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:8755)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at rt (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:3:10845)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at Oo.fireClose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:12622)
	at Socket.<anonymous> (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:14174)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Info  - 00:07:32] VLS Version: 0.0.1-56b3f92, OS: windows 64
[Info  - 00:07:32] Client / Editor: Visual Studio Code 1.60.2
[Info  - 00:07:32] Using V path (VROOT): C:\Users\marco\Documents\v
print_backtrace_skipping_top_frames_mingw is not implemented
[Info  - 00:07:32] Connection to server got closed. Server will restart.
[Error - 00:07:32] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:29:4057)
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:34:9518)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:9073)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:39:12267)
	at n (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:8755)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at rt (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:3:10845)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at Oo.fireClose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:12622)
	at Socket.<anonymous> (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:14174)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 00:07:32] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:29:4057)
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:34:9518)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:9073)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:39:12267)
	at n (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:8755)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at rt (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:3:10845)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at Oo.fireClose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:12622)
	at Socket.<anonymous> (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:14174)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Info  - 00:07:32] VLS Version: 0.0.1-56b3f92, OS: windows 64
[Info  - 00:07:32] Client / Editor: Visual Studio Code 1.60.2
[Info  - 00:07:32] Using V path (VROOT): C:\Users\marco\Documents\v
print_backtrace_skipping_top_frames_mingw is not implemented
[Error - 00:07:34] Connection to server got closed. Server will not be restarted.
[Error - 00:07:34] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:29:4057)
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:34:9518)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:9073)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:39:12267)
	at n (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:8755)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at rt (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:3:10845)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at Oo.fireClose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:12622)
	at Socket.<anonymous> (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:14174)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 00:07:34] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:29:4057)
	at Object.dispose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:34:9518)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:9073)
	at Mf.handleConnectionClosed (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:39:12267)
	at n (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:36:8755)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at rt (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:3:10845)
	at gu.invoke (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:9583)
	at Cr.fire (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:10348)
	at Oo.fireClose (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:12622)
	at Socket.<anonymous> (c:\Users\marco\.vscode\extensions\vlanguage.vscode-vlang-0.1.9\out\extension.js:2:14174)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
`

**Comment by nedpals** [comment]
@Piruzzolo There is an ongoing PR (#222 ) that we are trying to complete in order to parse the whole V codebase. May I ask what file in the V folder did you open?

CC @yuyi98

**Comment by Piruzzolo** [comment]
@nedpals sure, It was blog.v in the vweb tutorial foldet

**Comment by yuyi98** [comment]
It's ok.

![image](https://user-images.githubusercontent.com/6949593/134503669-59030b39-d28c-4b0d-95c7-c14d880c1fc6.png)

**Comment by Piruzzolo** [comment]
@yuyi98 maybe some misconfig on my part? Dos you do something special?

**Comment by JalonSolov** [comment]
Try https://blog.vosca.dev/meet-v-analyzer/ instead, now that it is released.
