### ISSUE TITLE
Recurring crashes

### ISSUE THREAD

**Issue by lukasl-dev** [vlang/vls#288]
### V doctor
```
OS: windows, Microsoft Windows 10 Pro v19043 64-bit
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the specified file.
 cmd: cc --version

getwd: C:\Users\lkasl\.vls\bin
vmodules: C:\Users\lkasl\.vmodules
vroot: C:\Program Files\vlang
vexe: C:\Program Files\vlang\v.exe
vexe mtime: 2021-12-02 13:35:22
is vroot writable: false
is vmodules writable: true
V full version: V 0.2.4 66a67de

Git version: git version 2.32.0.windows.1
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false
thirdparty/tcc status: thirdparty-windows-amd64 0f5168cd
```

### VLS info 
```
vls version 0.0.1.
```

## Problem Description
I was about to use the V programming language in combination with VLS and VSCode, but the server repeatedly crashes.

## Expected Output
Autocompletion of my user input

## Actual Output
Server crashes

## Steps to Reproduce
```v
fn main() {
	
}
```
This is the content of my main.v file.

## Last Recorded LSP Requests
```
[Error - 19:43:26] Request textDocument/codeLens failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\lkasl\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:29:4057)
    at Object.dispose (c:\Users\lkasl\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:34:9518)
    at Uf.handleConnectionClosed (c:\Users\lkasl\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:36:9070)
    at Uf.handleConnectionClosed (c:\Users\lkasl\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:39:12255)
    at n (c:\Users\lkasl\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:36:8752)
    at Tu.invoke (c:\Users\lkasl\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:9583)
    at wr.fire (c:\Users\lkasl\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:10348)
    at it (c:\Users\lkasl\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:3:10845)
    at Tu.invoke (c:\Users\lkasl\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:9583)
    at wr.fire (c:\Users\lkasl\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:10348)
    at Ao.fireClose (c:\Users\lkasl\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:12622)
    at Socket.<anonymous> (c:\Users\lkasl\.vscode-insiders\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:14174)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
[Error - 19:43:26] Connection to server is erroring. Shutting down server.
```

**Comment by nedpals** [comment]
cc @yuyi98

**Comment by yuyi98** [comment]
I don't have that problem.

> vexe: C:\Program Files\vlang\v.exe

I think vlang is best not installed on `C:\Program Files`.

**Comment by nedpals** [comment]
@yuyi98 I just remembered crash reporting is not yet working on Windows because of the missing WIP stufff in https://github.com/vlang/v/blob/master/vlib/os/process_windows.c.v. This should probably be done immediately so that we can identify this problem.

**Comment by yuyi98** [comment]
@nedpals  Yes, you're right, I'll try to resolve it.
