### ISSUE TITLE
Request textDocument/codeLens failed

### ISSUE THREAD

**Issue by skarab42** [vlang/vls#308]
While testing VSL I have an error that occurs in a strange way. When I save a file for the first time (after a modification) all goes well, the file is saved and formatted correctly. But when I start to edit the file again I get the following error in the V Language Server output.

<details>
  <summary>V Language Server output</summary>

  ```
  [Info  - 14:01:08] VLS Version: 0.0.1., OS: windows 64
  [Info  - 14:01:08] VLS executable path: C:\Users\skarab\.vls\bin\vls.exe
  [Info  - 14:01:08] VLS build with V b2f9842
  [Info  - 14:01:08] Client / Editor: Visual Studio Code 1.64.2 (PID: 15176)
  [Info  - 14:01:08] Using V path (VROOT): C:\Users\skarab\Coding\VLang\v
  19: RtlIsZeroMemory            ?? : address = 0x21070a96cb0
  18: RtlpNtSetValueKey          ?? : address = 0x21070a96c10
  17: RtlpNtSetValueKey          ?? : address = 0x21070a96b40
  16: RtlpNtSetValueKey          ?? : address = 0x21070a96b90
  15: RtlGetCurrentServiceSessionId  ?? : address = 0x21070a96b20
  14: RtlFreeHeap                ?? : address = 0x21070a96b80
  13: free_base                  ?? : address = 0x21070a96a70
  12: analyzer__ScopeTree_free   ?? : address = 0x21070a96a00
  11: analyzer__ScopeTree_free   ?? : address = 0x21070a96cc0
  10: analyzer__Store_delete_symbol_at_node  ?? : address = 0x21070a96a60
  9 : realloc_data               ?? : address = 0x21070a96ab0
  8 : server__Vls_dispatch       ?? : address = 0x21070a96a30
  7 : main__Stdio_receive        ?? : address = 0x21070a96b50
  6 : main__Stdio_receive        ?? : address = 0x21070a96c40
  5 : cli__Command_parse         ?? : address = 0x21070a969b0
  4 : main__Stdio_receive        ?? : address = 0x21070a96970
  3 : wmain                      ?? : address = 0x21070a968f0
  2 : __scrt_common_main_seh     d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  1 : BaseThreadInitThunk        ?? : address = 0x21070a96ba0
  0 : RtlUserThreadStart         ?? : address = 0x21070a96950
  [Info  - 14:01:32] Connection to server got closed. Server will restart.
  [Error - 14:01:32] Request textDocument/codeLens failed.
  Error: Connection got disposed.
	  at Object.dispose (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:29:4057)
	  at Object.dispose (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:34:9518)
	  at Uf.handleConnectionClosed (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:36:9070)
	  at Uf.handleConnectionClosed (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:39:12255)
	  at n (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:36:8752)
	  at Tu.invoke (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:9583)
	  at wr.fire (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:10348)
	  at it (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:3:10845)
	  at Tu.invoke (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:9583)
	  at wr.fire (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:10348)
	  at Ao.fireClose (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:12622)
	  at Socket.<anonymous> (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:14174)
	  at Socket.emit (events.js:327:22)
	  at Pipe.<anonymous> (net.js:673:12)
  [Error - 14:01:32] Request textDocument/codeLens failed.
  Error: Connection got disposed.
	  at Object.dispose (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:29:4057)
	  at Object.dispose (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:34:9518)
	  at Uf.handleConnectionClosed (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:36:9070)
	  at Uf.handleConnectionClosed (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:39:12255)
	  at n (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:36:8752)
	  at Tu.invoke (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:9583)
	  at wr.fire (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:10348)
	  at it (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:3:10845)
	  at Tu.invoke (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:9583)
	  at wr.fire (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:10348)
	  at Ao.fireClose (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:12622)
	  at Socket.<anonymous> (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:14174)
	  at Socket.emit (events.js:327:22)
	  at Pipe.<anonymous> (net.js:673:12)
  [Error - 14:01:32] Request textDocument/codeLens failed.
  Error: Connection got disposed.
	  at Object.dispose (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:29:4057)
	  at Object.dispose (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:34:9518)
	  at Uf.handleConnectionClosed (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:36:9070)
	  at Uf.handleConnectionClosed (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:39:12255)
	  at n (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:36:8752)
	  at Tu.invoke (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:9583)
	  at wr.fire (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:10348)
	  at it (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:3:10845)
	  at Tu.invoke (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:9583)
	  at wr.fire (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:10348)
	  at Ao.fireClose (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:12622)
	  at Socket.<anonymous> (c:\Users\skarab\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:2:14174)
	  at Socket.emit (events.js:327:22)
	  at Pipe.<anonymous> (net.js:673:12)
  [Error - 14:01:32] Connection to server is erroring. Shutting down server.
  ```
</details>

Plus the [vls.log](https://github.com/vlang/vscode-vlang/files/8060952/vls.log) file if it can help.

and my vscode config

```json
{
  "v.vls.debug": true,
  "v.vls.enable": true,
  "v.vls.customVrootPath": "C:\\Users\\skarab\\Coding\\VLang\\v",
  "[v]": {
    "editor.defaultFormatter": "vlanguage.vscode-vlang",
    "editor.formatOnSave": true
  }
}
```

**Comment by itsMapleLeaf** [comment]
I'm temporarily working around this by reverting to an earlier commit:
```bash
cd ~/.vls
git checkout 6dda1e2e9e6a0a13e6ab5321fca3185cf3660337
v run build.vsh
```

**Comment by nedpals** [comment]
@itsMapleLeaf can you post yours on a separate issue? this issue can be similar but it is using an older commit of VLS.

**Comment by itsMapleLeaf** [comment]
After updating the vls, I'm no longer running into this :+1:

**Comment by nedpals** [comment]
That's great to hear. We'll close this issue 🙂
