### ISSUE TITLE
Connection to server got closed，request textDocument/documentSymbol failed

### ISSUE THREAD

**Issue by tzSharing** [vlang/vls#375]
### V doctor
```
OS: windows, Microsoft Windows 10 ҵ v19043 64 λ
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz
CC version: Error: exec failed (CreateProcess) with code 2: 系统找不到指定的文件。
 cmd: cc --version

getwd: C:\Users\TZ
vmodules: C:\Users\TZ\.vmodules
vroot: D:\v
vexe: D:\v\v.exe
vexe mtime: 2022-07-31 10:15:42
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 b8438de

Git version: git version 2.34.1.windows.1
Git vroot status: weekly.2022.30-36-gb8438ded
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 125e21e2
```

### VLS info 
```
VLS Version: 0.0.1.79e749f
```

## Problem Description
This is a sporadic bug, restarting VS Code will return to normal, but sometimes it will reappear.
```
[Info  - 19:03:59] VLS Version: 0.0.1.79e749f, OS: windows 64
[Info  - 19:03:59] VLS executable path: C:\Users\TZ\.vls\bin\vls.exe
[Info  - 19:03:59] VLS build with V b8438de
[Info  - 19:03:59] Client / Editor: Visual Studio Code 1.69.2 (PID: 2596)
[Info  - 19:03:59] Using V path (VROOT): D:\v
[Info  - 19:03:59] is_logger_installed: true | is_logger_enabled: false | params.trace: off
[Info  - 19:04:06] Connection to server got closed. Server will restart.
[Error - 19:04:06] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\TZ\.vscode\extensions\vlanguage.vscode-vlang-0.1.13\out\extension.js:29:4057)
	at Object.dispose (c:\Users\TZ\.vscode\extensions\vlanguage.vscode-vlang-0.1.13\out\extension.js:34:9518)
	at Vf.handleConnectionClosed (c:\Users\TZ\.vscode\extensions\vlanguage.vscode-vlang-0.1.13\out\extension.js:36:9070)
	at Vf.handleConnectionClosed (c:\Users\TZ\.vscode\extensions\vlanguage.vscode-vlang-0.1.13\out\extension.js:39:12201)
	at n (c:\Users\TZ\.vscode\extensions\vlanguage.vscode-vlang-0.1.13\out\extension.js:36:8752)
	at Pu.invoke (c:\Users\TZ\.vscode\extensions\vlanguage.vscode-vlang-0.1.13\out\extension.js:2:9583)
	at Tr.fire (c:\Users\TZ\.vscode\extensions\vlanguage.vscode-vlang-0.1.13\out\extension.js:2:10348)
	at it (c:\Users\TZ\.vscode\extensions\vlanguage.vscode-vlang-0.1.13\out\extension.js:3:10845)
	at Pu.invoke (c:\Users\TZ\.vscode\extensions\vlanguage.vscode-vlang-0.1.13\out\extension.js:2:9583)
	at Tr.fire (c:\Users\TZ\.vscode\extensions\vlanguage.vscode-vlang-0.1.13\out\extension.js:2:10348)
	at jo.fireClose (c:\Users\TZ\.vscode\extensions\vlanguage.vscode-vlang-0.1.13\out\extension.js:2:12622)
	at Socket.<anonymous> (c:\Users\TZ\.vscode\extensions\vlanguage.vscode-vlang-0.1.13\out\extension.js:2:14174)
	at Socket.emit (node:events:402:35)
	at Pipe.<anonymous> (node:net:687:12)
```

**Comment by nedpals** [comment]
@tzSharing Was there any message that a crash log has been generated?

**Comment by JalonSolov** [comment]
Also, look to see if you have any files matching `C:\Users\TZ\vls_*`

**Comment by nedpals** [comment]
It's inside `%USERDIR%\.vls\logs` on the recent versions

**Comment by tzSharing** [comment]
@nedpals @JalonSolov I only found the vls report file under `C:\Users\TZ\\.vls\reports`, I have uploaded it, hope it helps.
[vls_report_1659263561.md](https://github.com/vlang/vls/files/9232055/vls_report_1659263561.md)
[vls_report_1659265442.md](https://github.com/vlang/vls/files/9232058/vls_report_1659265442.md)

**Comment by nedpals** [comment]
Great! I'll look into this later. Thanks 🙂

**Comment by JalonSolov** [comment]
Try https://blog.vosca.dev/meet-v-analyzer/ instead, now that it is released.
