### ISSUE TITLE
vls crash report

### ISSUE THREAD

**Issue by zhwei820** [vlang/vls#388]
vs code output.
```

[Info  - 9:36:29 AM] VLS Version: 0.0.1.93767cb, OS: macos 64
[Info  - 9:36:29 AM] VLS executable path: /Users/zhouw/.vls/bin/vls_macos_x64
[Info  - 9:36:29 AM] VLS build with V 728b198
[Info  - 9:36:29 AM] Client / Editor: Visual Studio Code 1.71.2 (PID: 6931)
[Info  - 9:36:29 AM] Using V path (VROOT): /Users/zhouw/v/
[Info  - 9:36:29 AM] is_logger_installed: true | is_logger_enabled: true | params.trace: off
[Info  - 9:36:31 AM] Connection to server got closed. Server will restart.
[Error - 9:36:31 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:29:4041)
	at Object.dispose (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:34:9518)
	at mc.handleConnectionClosed (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:36:9054)
	at mc.handleConnectionClosed (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:39:12095)
	at n (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:36:8736)
	at Jo.invoke (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:2:9583)
	at Jn.fire (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:2:10348)
	at it (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:3:10845)
	at Jo.invoke (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:2:9583)
	at Jn.fire (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:2:10348)
	at wi.fireClose (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:3:523)
	at Socket.<anonymous> (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:3:1297)
	at Socket.emit (node:events:526:28)
	at Pipe.<anonymous> (node:net:687:12)
[Error - 9:36:31 AM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:29:4041)
	at Object.dispose (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:34:9518)
	at mc.handleConnectionClosed (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:36:9054)
	at mc.handleConnectionClosed (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:39:12095)
	at n (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:36:8736)
	at Jo.invoke (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:2:9583)
	at Jn.fire (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:2:10348)
	at it (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:3:10845)
	at Jo.invoke (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:2:9583)
	at Jn.fire (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:2:10348)
	at wi.fireClose (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:3:523)
	at Socket.<anonymous> (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:3:1297)
	at Socket.emit (node:events:526:28)
	at Pipe.<anonymous> (node:net:687:12)
[Error - 9:36:31 AM] Request textDocument/foldingRange failed.
Error: Connection got disposed.
	at Object.dispose (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:29:4041)
	at Object.dispose (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:34:9518)
	at mc.handleConnectionClosed (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:36:9054)
	at mc.handleConnectionClosed (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:39:12095)
	at n (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:36:8736)
	at Jo.invoke (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:2:9583)
	at Jn.fire (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:2:10348)
	at it (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:3:10845)
	at Jo.invoke (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:2:9583)
	at Jn.fire (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:2:10348)
	at wi.fireClose (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:3:523)
	at Socket.<anonymous> (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:3:1297)
	at Socket.emit (node:events:526:28)
	at Pipe.<anonymous> (node:net:687:12)
[Error - 9:36:31 AM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:29:4041)
	at Object.dispose (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:34:9518)
	at mc.handleConnectionClosed (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:36:9054)
	at mc.handleConnectionClosed (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:39:12095)
	at n (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:36:8736)
	at Jo.invoke (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:2:9583)
	at Jn.fire (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:2:10348)
	at it (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:3:10845)
	at Jo.invoke (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:2:9583)
	at Jn.fire (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:2:10348)
	at wi.fireClose (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:3:523)
	at Socket.<anonymous> (/Users/zhouw/.vscode/extensions/vlanguage.vscode-vlang-0.1.14/out/extension.js:3:1297)
	at Socket.emit (node:events:526:28)
	at Pipe.<anonymous> (node:net:687:12)
[Info  - 9:36:31 AM] Connection to server got closed. Server will restart.


```

### V doctor
```
OS: macos, macOS, 12.6, 21G115
Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
CC version: Apple clang version 12.0.5 (clang-1205.0.22.11)

getwd: /
vmodules: /Users/zhouw/.vmodules
vroot: /Users/zhouw/v
vexe: /Users/zhouw/v/v
vexe mtime: 2022-09-20 10:08:33
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.1 993802f

Git version: git version 2.30.1 (Apple Git-130)
Git vroot status: weekly.2022.38 (23 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-macos-amd64 46662e20
```

### VLS info 
```
vls version: 0.0.1.93767cb
vls server arguments: --child --socket --debug --port 5008 --vroot /Users/zhouw/v/ --timeout 15
```

## Actual Output
N/A

### Request
```
[2022-09-24 01:36:29] {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":6931,"clientInfo":{"name":"Visual Studio Code","version":"1.71.2"},"locale":"en-us","rootPath":"/Users/zhouw/www/local_test/v/pkg","rootUri":"file:///Users/zhouw/www/local_test/v/pkg","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional","normalizesLineEndings":true,"changeAnnotationSupport":{"groupsOnLabel":true}},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]}},"codeLens":{"refreshSupport":true},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true,"semanticTokens":{"refreshSupport":true},"fileOperations":{"dynamicRegistration":true,"didCreate":true,"didRename":true,"didDelete":true,"willCreate":true,"willRename":true,"willDelete":true}},"textDocument":{"publishDiagnostics":{"relatedInformation":true,"versionSupport":false,"tagSupport":{"valueSet":[1,2]},"codeDescriptionSupport":true,"dataSupport":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true,"tagSupport":{"valueSet":[1]},"insertReplaceSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"insertTextModeSupport":{"valueSet":[1,2]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true},"activeParameterSupport":true},"contextSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true,"tagSupport":{"valueSet":[1]},"labelSupport":true},"codeAction":{"dynamicRegistration":true,"isPreferredSupport":true,"disabledSupport":true,"dataSupport":true,"resolveSupport":{"properties":["edit"]},"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"honorsChangeAnnotations":false},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true,"prepareSupportDefaultBehavior":1,"honorsChangeAnnotations":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"selectionRange":{"dynamicRegistration":true},"callHierarchy":{"dynamicRegistration":true},"semanticTokens":{"dynamicRegistration":true,"tokenTypes":["namespace","type","class","enum","interface","struct","typeParameter","parameter","variable","property","enumMember","event","function","method","macro","keyword","modifier","comment","string","number","regexp","operator"],"tokenModifiers":["declaration","definition","readonly","static","deprecated","abstract","async","modification","documentation","defaultLibrary"],"formats":["relative"],"requests":{"range":true,"full":{"delta":true}},"multilineTokenSupport":false,"overlappingTokenSupport":false},"linkedEditingRange":{"dynamicRegistration":true}},"window":{"showMessage":{"messageActionItem":{"additionalPropertiesSupport":true}},"showDocument":{"support":true},"workDoneProgress":true},"general":{"regularExpressions":{"engine":"ECMAScript","version":"ES2020"},"markdown":{"parser":"marked","version":"1.1.0"}}},"trace":"off","workspaceFolders":[{"uri":"file:///Users/zhouw/www/local_test/v/pkg","name":"pkg"}]}}

[2022-09-24 01:36:30] {"jsonrpc":"2.0","method":"initialized","params":{}}

[2022-09-24 01:36:30] {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///Users/zhouw/www/local_test/v/pkg/simple.v","languageId":"v","version":1,"text":"//单行注释\n/*\n多行注释\n多行注释\n*/\n//定义主模块，编译生成可执行程序\nmodule main\n\n//导入模块\nimport os\nimport time\n\n//主函数，程序运行入口\npub fn main() {\n\tprintln('say hello world') // 语句结尾不需要分号\n\tprintln(os.args) // 使用os模块的args变量\n\tprintln(time.now()) // 调用time模块的now函数\n\n\tgo my_fn(1, 2) // 跟go一样的并发\n\n\tmy_fn2(1) // 匿名联合类型作为参数或返回值\n\n\tmy_fn3(0) or { // or代码块,进行错误处理\n\t\tpanic(err.msg())\n\t}\n}\n\n//模块内6个一级元素：常量，枚举，函数/方法，结构体，接口，类型\n// 1.常量\n// 单行常量\npub const usage = 'usage ...'\n\n// 常量组\npub const (\n\tversion             = '0.1.21'\n\tsupported_platforms = ['windows', 'mac', 'linux']\n)\n\n// 2.枚举\npub enum OS {\n\tmac\n\tlinux\n\twindows\n}\n\n// 3.函数-函数定义\n// 函数的定义风格基本跟go一样，只是关键字改为更简短的fn，支持不确定个数参数，支持多返回值\n// pub表示公共级别的访问控制，可以被模块外使用，否则只能在模块内使用\npub fn my_fn(x int, y int) int {\n\ti := 1 //强类型，类型推断\n\ts := 'abc' //变量默认不可变，约定用单引号表示字符串，双引号也可以，反引号才是单字符\n\tmut a := 3 //可变用mut\n\ta = 5 //声明可变后，才可修改\n\tprintln(i)\n\tprintln(s)\n\treturn a\n}\n\n// 3.函数-匿名联合类型作为参数或返回值\npub fn my_fn2(x int|string|bool) int|string|bool {\n\tprintln(x)\n\treturn x\n}\n\n// 3.函数-简洁的错误处理\npub fn my_fn3(x int) !int {\n\tif x == 0 {\n\t\treturn error('this is an error.') // 抛出错误,然后在调用函数的or代码块进行错误处理\n\t}\n\treturn x\n}\n\n// 3.函数-泛型函数\npub fn g_fn<T, U>(x T, y U) (T, U) {\n\treturn x, y\n}\n\n// 3.方法-方法只是指定了接收者的函数，跟go一样\npub fn (mut p Point) move(x int, y int) {\n\tp.x += x\n\tp.y += y\n}\n\n// 4.结构体-结构体定义\npub struct Point {\n\t//结构体字段一共有5种访问控制\n\t// 1.默认私有且不可变\n\ta int\n\t// 2.私有，但可变\nmut:\n\tx int\n\ty int\n\t// 3.公共，但不可变\npub:\n\td int\n\t// 4.模块内可访问且可变;模块外可访问，但是只读\npub mut:\n\te int\n\t// 5.全局字段，模块内部和外部都可访问，可修改，这样等于破坏了封装性，不推荐使用\n__global:\n\tf int\n}\n\n// 4.结构体-泛型结构体\npub struct Repo<T> {\n\tdb DB\nmut:\n\tmodel T\n}\n\npub struct DB {\n}\n\n// 5.接口-接口无须显式声明实现，鸭子类型，跟go一样\npub interface Walker {\n\tname string //接口支持字段约束,表示实现该接口的结构体必须有该字段\n\twalk(int, int) int\n}\n\n// 5.接口-泛型接口，跟泛型结构体使用基本一致\npub interface Gettable<T> {\n\tget() T\n}\n\n// 6.类型-类型别名，可以基于基本类型，也可基于结构体类型创建类型别名\npub type Myint = int\n\n// 6.类型-函数类型，表示一类相同签名的函数\npub type Fn_type = fn (int) int\n\n// 6.类型-联合类型，跟typescript类似，表示类型Expr可以是这几种类型的其中一种\npub struct BinExpr {}\n\npub struct BoolExpr {}\n\npub struct UnaryExpr {}\n\npub type Expr = BinExpr | BoolExpr | UnaryExpr\n\n// 6.类型-泛型联合类型\npub type MyOption<T> = Error | None | T\n\nstruct None {}\n"}}}

[2022-09-24 01:36:30] {"jsonrpc":"2.0","id":1,"method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///Users/zhouw/www/local_test/v/pkg/simple.v"}}}

[2022-09-24 01:36:30] {"jsonrpc":"2.0","id":2,"method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///Users/zhouw/www/local_test/v/pkg/simple.v"}}}

[2022-09-24 01:36:30] {"jsonrpc":"2.0","id":3,"method":"textDocument/foldingRange","params":{"textDocument":{"uri":"file:///Users/zhouw/www/local_test/v/pkg/simple.v"}}}

[2022-09-24 01:36:31] {"jsonrpc":"2.0","id":4,"method":"textDocument/codeLens","params":{"textDocument":{"uri":"file:///Users/zhouw/www/local_test/v/pkg/simple.v"}}}
```
### Response
```
[2022-09-24 01:36:29] {"jsonrpc":"2.0","method":"window/showMessage","params":{"type":2,"message":"VLS is early software. Please report your issue to github.com/vlang/vls if you encounter any problems."}}

[2022-09-24 01:36:29] {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"VLS Version: 0.0.1.93767cb, OS: macos 64"}}

[2022-09-24 01:36:29] {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"VLS executable path: /Users/zhouw/.vls/bin/vls_macos_x64"}}

[2022-09-24 01:36:29] {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"VLS build with V 728b198"}}

[2022-09-24 01:36:29] {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"Client / Editor: Visual Studio Code 1.71.2 (PID: 6931)"}}

[2022-09-24 01:36:29] {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"Using V path (VROOT): /Users/zhouw/v/"}}

[2022-09-24 01:36:29] {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"is_logger_installed: true | is_logger_enabled: true | params.trace: off"}}

[2022-09-24 01:36:30] {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":2,"hoverProvider":true,"completionProvider":{"resolveProvider":false,"triggerCharacters":["=",".",":","{",",","("," "]},"signatureHelpProvider":{"triggerCharacters":["("],"retriggerCharacters":[","," "]},"definitionProvider":true,"typeDefinitionProvider":false,"implementationProvider":true,"referencesProvider":false,"documentHighlightProvider":false,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":false,"codeLensProvider":{"resolveProvider":false},"documentFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"","moreTriggerCharacter":[]},"renameProvider":false,"documentLinkProvider":{"resolveProvider":false},"colorProvider":false,"declarationProvider":false,"executeCommandProvider":{"commands":[]},"foldingRangeProvider":true,"experimental":{}}}}

[2022-09-24 01:36:30] {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/zhouw/www/local_test/v/pkg/simple.v","diagnostics":[]}}

[2022-09-24 01:36:30] {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/zhouw/www/local_test/v/pkg/simple.v","diagnostics":[{"range":{"start":{"line":9,"character":7},"end":{"line":9,"character":9}},"severity":1,"code":"","source":"","message":"Module `[analyzer.Import{\n    resolved: false\n    imported: false\n    absolute_module_name: 'lo'\n    module_name: 'lo'\n    path: ''\n    ranges: {'/Users/zhouw/www/local_test/v/pkg/simple.v': TSRange{\n        start_point: TSPoint{\n            row: 9\n            column: 7\n        }\n        end_point: TSPoint{\n            row: 9\n            column: 9\n        }\n        start_byte: 130\n        end_byte: 132\n    }}\n    aliases: {}\n    symbols: {}\n}, analyzer.Import{\n    resolved: false\n    imported: false\n    absolute_module_name: ' // '\n    module_name: ' // '\n    path: ''\n    ranges: {'/Users/zhouw/www/local_test/v/pkg/simple.v': TSRange{\n        start_point: TSPoint{\n            row: 10\n            column: 7\n        }\n        end_point: TSPoint{\n            row: 10\n            column: 11\n        }\n        start_byte: 140\n        end_byte: 144\n    }}\n    aliases: {}\n    symbols: {}\n}][import_idx].absolute_module_name` not found","relatedInformation":[]},{"range":{"start":{"line":10,"character":7},"end":{"line":10,"character":11}},"severity":1,"code":"","source":"","message":"Module `[analyzer.Import{\n    resolved: false\n    imported: false\n    absolute_module_name: 'lo'\n    module_name: 'lo'\n    path: ''\n    ranges: {}\n    aliases: {}\n    symbols: {}\n}, analyzer.Import{\n    resolved: false\n    imported: false\n    absolute_module_name: ' // '\n    module_name: ' // '\n    path: ''\n    ranges: {'/Users/zhouw/www/local_test/v/pkg/simple.v': TSRange{\n        start_point: TSPoint{\n            row: 10\n            column: 7\n        }\n        end_point: TSPoint{\n            row: 10\n            column: 11\n        }\n        start_byte: 140\n        end_byte: 144\n    }}\n    aliases: {}\n    symbols: {}\n}][import_idx].absolute_module_name` not found","relatedInformation":[]}]}}

[2022-09-24 01:36:30] {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/zhouw/www/local_test/v/pkg/pkg.v","diagnostics":[]}}

[2022-09-24 01:36:30] {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/zhouw/www/local_test/v/pkg/simple.v","diagnostics":[]}}

[2022-09-24 01:36:30] {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/zhouw/www/local_test/v/pkg/simple.v","diagnostics":[{"range":{"start":{"line":9,"character":7},"end":{"line":9,"character":9}},"severity":1,"code":"","source":"","message":"Module `[analyzer.Import{\n    resolved: false\n    imported: false\n    absolute_module_name: 'lo'\n    module_name: 'lo'\n    path: ''\n    ranges: {'/Users/zhouw/www/local_test/v/pkg/simple.v': TSRange{\n        start_point: TSPoint{\n            row: 9\n            column: 7\n        }\n        end_point: TSPoint{\n            row: 9\n            column: 9\n        }\n        start_byte: 130\n        end_byte: 132\n    }}\n    aliases: {}\n    symbols: {}\n}, analyzer.Import{\n    resolved: false\n    imported: false\n    absolute_module_name: ' // '\n    module_name: ' // '\n    path: ''\n    ranges: {'/Users/zhouw/www/local_test/v/pkg/simple.v': TSRange{\n        start_point: TSPoint{\n            row: 10\n            column: 7\n        }\n        end_point: TSPoint{\n            row: 10\n            column: 11\n        }\n        start_byte: 140\n        end_byte: 144\n    }}\n    aliases: {}\n    symbols: {}\n}][import_idx].absolute_module_name` not found","relatedInformation":[]},{"range":{"start":{"line":10,"character":7},"end":{"line":10,"character":11}},"severity":1,"code":"","source":"","message":"Module `[analyzer.Import{\n    resolved: false\n    imported: false\n    absolute_module_name: 'lo'\n    module_name: 'lo'\n    path: ''\n    ranges: {}\n    aliases: {}\n    symbols: {}\n}, analyzer.Import{\n    resolved: false\n    imported: false\n    absolute_module_name: ' // '\n    module_name: ' // '\n    path: ''\n    ranges: {'/Users/zhouw/www/local_test/v/pkg/simple.v': TSRange{\n        start_point: TSPoint{\n            row: 10\n            column: 7\n        }\n        end_point: TSPoint{\n            row: 10\n            column: 11\n        }\n        start_byte: 140\n        end_byte: 144\n    }}\n    aliases: {}\n    symbols: {}\n}][import_idx].absolute_module_name` not found","relatedInformation":[]},{"range":{"start":{"line":59,"character":16},"end":{"line":59,"character":16}},"severity":2,"code":"","source":"","message":"inline sum types have been deprecated and will be removed on January 1, 2023 due to complicating the language and the compiler too much; define named sum types with `type Foo = Bar | Baz` instead","relatedInformation":[]},{"range":{"start":{"line":59,"character":33},"end":{"line":59,"character":33}},"severity":2,"code":"","source":"","message":"inline sum types have been deprecated and will be removed on January 1, 2023 due to complicating the language and the compiler too much; define named sum types with `type Foo = Bar | Baz` instead","relatedInformation":[]}]}}
```

## Posible causes
      There are two `main functions` in same package; when I remove one `main function`, it stops crash.

**Comment by JalonSolov** [comment]
Try https://blog.vosca.dev/meet-v-analyzer/ instead, now that it is released.
