### ISSUE TITLE
VLS crash when you write something

### ISSUE THREAD

**Issue by nightway1** [vlang/vls#447]
### 
```
V full version: V 0.4.2 97f7c3f
OS: linux, "Arch Linux"
Processor: 12 cpus, 64bit, little endian, AMD Ryzen 5 5600G with Radeon Graphics

getwd: /home/wayfinder/Documentos/dev/programacion/vlang/five_nights_at_1_kb
vexe: /usr/bin/vlang/v
vexe mtime: 2023-11-09 02:58:47

vroot: OK, value: /usr/bin/vlang
VMODULES: OK, value: /home/wayfinder/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.42.1
Git vroot status: Error: fatal: no es un repositorio git (ni ninguno de los directorios superiores): .git
.git/config present: false

CC version: cc (GCC) 13.2.1 20230801
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```

### VLS info 
```
vls version 0.0.1.d145a6d
```

## Problem Description
its no general bug, only in this moment when i write the match keyword the vls crash, here is the code makes it crash:
```
const office_frames = {
	'empty_office':                  '
_______________________________
|        _____________        |
|        |           |        |
|        |           |        |
|        |           |        |
|        |           |        |
|        |           |        |
|        |           |        |
|    ____|___________|____    |
|   /                     \\   |
|  /                       \\  |
| /                         \\ |
|/___________________________\\|'
	'light_office':                  '
_______________________________
|        _____________        |
|        |░░░░░░░░░░░|        |
|        |░░░░░░░░░░░|        |
|        |░░░░░░░░░░░|        |
|        |░░░░░░░░░░░|        |
|        |░░░░░░░░░░░|        |
|        |░░░░░░░░░░░|        |
|    ____|░░░░░░░░░░░|____    |
|   /                     \\   |
|  /                       \\  |
| /                         \\ |
|/___________________________\\|'
	'light_office_with_animatronic': '
_______________________________
|        _____________        |
|        |░░░░░░░░░░░|        |
|        |░░|.\\_/.|░░|        |
|        |░░░░/|\\░░░░|        |
|        |░░░/░|░\\░░░|        |
|        |░░░░░|░░░░░|        |
|        |░░░░|░|░░░░|        |
|    ____|░░░░|░|░░░░|____    |
|   /                     \\   |
|  /                       \\  |
| /                         \\ |
|/___________________________\\|'
	'closed_door_office':            '
_______________________________
|        _____________        |
|        |███████████|        |
|        |███████████|        |
|        |███████████|        |
|        |███████████|        |
|        |███████████|        |
|        |███████████|        |
|    ____|███████████|____    |
|   /                     \\   |
|  /                       \\  |
| /                         \\ |
|/___________________________\\|'
}

enum OfficeState {
	empty
	light_on
	light_on_with_animatronic
	closed_door
}

fn win() {
}

fn loose() {
}

fn play_sound() {
}

fn print_office(office_state OfficeState) {
	mut office_frame := ""
        match
	
}

pub fn game_loop(difficutly u8) {
}

```

## Expected Output
nothing should be happen

## Actual Output
```
[Info  - 18:11:39] VLS Version: 0.0.1.d145a6d, OS: linux 64
[Info  - 18:11:40] VLS executable path: /home/wayfinder/.vls/bin/vls_linux_x64
[Info  - 18:11:40] VLS build with V 1f8fbb5
[Info  - 18:11:40] Client / Editor: VSCodium 1.84.0 (PID: 40116)
[Info  - 18:11:40] Using V path (VROOT): /usr/bin/vlang
[Info  - 18:11:40] is_logger_installed: true | is_logger_enabled: false | params.trace: off
[Info  - 18:11:42] Connection to server got closed. Server will restart.
[Error - 18:11:42] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:29:4041)
	at Object.dispose (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:34:9518)
	at mc.handleConnectionClosed (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:36:9054)
	at mc.handleConnectionClosed (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:39:12095)
	at n (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:36:8736)
	at Jo.invoke (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:9583)
	at Jn.fire (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:10348)
	at it (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:3:10845)
	at Jo.invoke (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:9583)
	at Jn.fire (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:10348)
	at wi.fireClose (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:3:523)
	at Socket.<anonymous> (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:3:1297)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:322:12)
[Error - 18:11:42] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:29:4041)
	at Object.dispose (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:34:9518)
	at mc.handleConnectionClosed (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:36:9054)
	at mc.handleConnectionClosed (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:39:12095)
	at n (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:36:8736)
	at Jo.invoke (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:9583)
	at Jn.fire (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:10348)
	at it (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:3:10845)
	at Jo.invoke (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:9583)
	at Jn.fire (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:10348)
	at wi.fireClose (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:3:523)
	at Socket.<anonymous> (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:3:1297)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:322:12)
[Error - 18:11:42] Request textDocument/foldingRange failed.
Error: Connection got disposed.
	at Object.dispose (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:29:4041)
	at Object.dispose (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:34:9518)
	at mc.handleConnectionClosed (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:36:9054)
	at mc.handleConnectionClosed (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:39:12095)
	at n (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:36:8736)
	at Jo.invoke (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:9583)
	at Jn.fire (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:10348)
	at it (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:3:10845)
	at Jo.invoke (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:9583)
	at Jn.fire (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:10348)
	at wi.fireClose (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:3:523)
	at Socket.<anonymous> (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:3:1297)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:322:12)
[Error - 18:11:42] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:29:4041)
	at Object.dispose (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:34:9518)
	at mc.handleConnectionClosed (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:36:9054)
	at mc.handleConnectionClosed (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:39:12095)
	at n (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:36:8736)
	at Jo.invoke (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:9583)
	at Jn.fire (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:10348)
	at it (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:3:10845)
	at Jo.invoke (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:9583)
	at Jn.fire (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:10348)
	at wi.fireClose (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:3:523)
	at Socket.<anonymous> (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:3:1297)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:322:12)
[Error - 18:11:42] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:29:4041)
	at Object.dispose (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:34:9518)
	at mc.handleConnectionClosed (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:36:9054)
	at mc.handleConnectionClosed (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:39:12095)
	at n (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:36:8736)
	at Jo.invoke (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:9583)
	at Jn.fire (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:10348)
	at it (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:3:10845)
	at Jo.invoke (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:9583)
	at Jn.fire (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:2:10348)
	at wi.fireClose (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:3:523)
	at Socket.<anonymous> (/home/wayfinder/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.14-universal/out/extension.js:3:1297)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:322:12)
[Info  - 18:11:42] Connection to server got closed. Server will restart.


```
## Steps to Reproduce
ok, at first I thought it was due to the simple fact of writing match in the code, then I thought it was due to having an enum type in the argument type of a variable, I no longer have any idea why it happens, the best thing would be to copy my code and do tests there, I don't understand anything

**Comment by ttytm** [comment]
If that's of any help for you: For IDE usage https://github.com/v-analyzer/v-analyzer is the recommended plugin, ref: https://github.com/vlang/v#editoride-plugins.
