### ISSUE TITLE
LSP does not work

### ISSUE THREAD

**Issue by koplenov** [vlang/vls#89]
#### I am use:

* VS Code [ February 2021 (version 1.54) ]
* [vlanguage.vscode-vlang v0.1.8](https://marketplace.visualstudio.com/items?itemName=vlanguage.vscode-vlang)
* v [ V 0.2.2 92f19f5 ]
* vls [ last at this moment  [last at this moment](https://github.com/vlang/vls/commit/4d510e3619109b5d655436a947d78f58506ff146)  ]

#### I want to use the LSP in VS Code and get this error:

<details>
  <summary>Error code (click to show)</summary>

```cmd
[Info  - 22:05:08] VLS Version: 0.0.1, OS: windows 64
[Info  - 22:05:08] Client / Editor: Visual Studio Code 1.54.3
print_backtrace_skipping_top_frames is not implemented
[Info  - 22:05:08] Connection to server got closed. Server will restart.
[Error - 22:05:08] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:39411)
	at Object.dispose (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119583)
	at w.handleConnectionClosed (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119796)
	at w.handleConnectionClosed (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:180184)
	at t (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:117885)
	at r.invoke (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at Y (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:28669)
	at r.invoke (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at fireClose (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:53238)
	at Socket.<anonymous> (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:54023)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:674:12)
[Error - 22:05:08] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:39411)
	at Object.dispose (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119583)
	at w.handleConnectionClosed (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119796)
	at w.handleConnectionClosed (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:180184)
	at t (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:117885)
	at r.invoke (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at Y (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:28669)
	at r.invoke (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at fireClose (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:53238)
	at Socket.<anonymous> (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:54023)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:674:12)
[Info  - 22:05:09] VLS Version: 0.0.1, OS: windows 64
[Info  - 22:05:09] Client / Editor: Visual Studio Code 1.54.3
print_backtrace_skipping_top_frames is not implemented
[Info  - 22:05:09] Connection to server got closed. Server will restart.
[Error - 22:05:09] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:39411)
	at Object.dispose (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119583)
	at w.handleConnectionClosed (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119796)
	at w.handleConnectionClosed (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:180184)
	at t (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:117885)
	at r.invoke (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at Y (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:28669)
	at r.invoke (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at m.fireClose (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:49666)
	at Socket.<anonymous> (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:51251)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:674:12)
[Info  - 22:05:09] VLS Version: 0.0.1, OS: windows 64
[Info  - 22:05:09] Client / Editor: Visual Studio Code 1.54.3
print_backtrace_skipping_top_frames is not implemented
[Info  - 22:05:09] Connection to server got closed. Server will restart.
[Error - 22:05:09] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:39411)
	at Object.dispose (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119583)
	at w.handleConnectionClosed (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119796)
	at w.handleConnectionClosed (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:180184)
	at t (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:117885)
	at r.invoke (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at Y (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:28669)
	at r.invoke (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at m.fireClose (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:49666)
	at Socket.<anonymous> (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:51251)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:674:12)
[Info  - 22:05:09] VLS Version: 0.0.1, OS: windows 64
[Info  - 22:05:09] Client / Editor: Visual Studio Code 1.54.3
print_backtrace_skipping_top_frames is not implemented
[Info  - 22:05:09] Connection to server got closed. Server will restart.
[Error - 22:05:09] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:39411)
	at Object.dispose (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119583)
	at w.handleConnectionClosed (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119796)
	at w.handleConnectionClosed (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:180184)
	at t (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:117885)
	at r.invoke (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at Y (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:28669)
	at r.invoke (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at m.fireClose (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:49666)
	at Socket.<anonymous> (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:51251)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:674:12)
[Info  - 22:05:09] VLS Version: 0.0.1, OS: windows 64
[Info  - 22:05:09] Client / Editor: Visual Studio Code 1.54.3
print_backtrace_skipping_top_frames is not implemented
[Error - 22:05:09] Connection to server got closed. Server will not be restarted.
[Error - 22:05:09] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:39411)
	at Object.dispose (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119583)
	at w.handleConnectionClosed (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:119796)
	at w.handleConnectionClosed (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:180184)
	at t (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:117885)
	at r.invoke (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at Y (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:28669)
	at r.invoke (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41024)
	at o.fire (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:41785)
	at m.fireClose (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:49666)
	at Socket.<anonymous> (c:\Users\koplenov\.vscode\extensions\vlanguage.vscode-vlang-0.1.8\out\extension.js:1:51251)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:674:12)
```

  
</details>

#### On this block of code:
```V
import vweb

struct App {
    vweb.Context
}

fn main() {
	vweb.run<App>(8080)
}

['/hello/:user']
fn (mut app App) hello_user(user string) vweb.Result {
    return app.text('Hello $user')
}
```

**Comment by nedpals** [comment]
Can't reproduce the issue. Works fine for me. @koplenov have you tried updating V and VLS once again?
